apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummygoapi
spec:
  selector:
    matchLabels:
      app: dummygoapi
  replicas: 2
  template:
    metadata:
      labels:
        app: dummygoapi
    spec:
      containers:
      - name: dummygoapi
        image: docker.io/andrewzah/go-test-api
        ports:
        - containerPort: 9090

